"""Apps themed through files: the Shell stylesheet, terminals, launcher, editor."""
import json
import pathlib
import re
import subprocess

from .. import themes
from ..store import File, Setting, config_home, data_home, read_text, state_home

MARK_BEGIN = '# >>> jade-theme (generated; edits here are replaced)'
MARK_END = '# <<< jade-theme'


def signal(process, sig):
    """Ask running instances to reload; quietly nothing when none run."""
    subprocess.run(['pkill', f'-{sig}', '-x', process], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def managed_block(text, block):
    """Replace (or append) our marked block, leaving the rest of the file alone."""
    wrapped = f'{MARK_BEGIN}\n{block.rstrip()}\n{MARK_END}\n'
    pattern = re.compile(re.escape(MARK_BEGIN) + r'.*?' + re.escape(MARK_END) + r'\n?', re.S)
    if pattern.search(text):
        return pattern.sub(lambda _m: wrapped, text)
    return text.rstrip('\n') + '\n\n' + wrapped


class Shell:
    name = 'shell'
    label = 'Workspaces bar, quick settings and Jade extensions'

    def available(self, ctx):
        return None

    def changes(self, theme, ctx):
        base = state_home() / 'jade-shell'
        colors = {'id': theme.id, 'name': theme.name, 'colors': theme.colors}
        return [
            File(base / 'shell.css', themes.render(themes.template('shell.css.tpl'), theme.colors)),
            File(base / 'colors.json', json.dumps(colors, indent=2, sort_keys=True) + '\n'),
        ]

    def reload(self, ctx):
        pass  # the Jade Shell extension watches these files


class Ptyxis:
    name = 'ptyxis'
    label = 'Ptyxis terminal palette'
    schema = 'org.gnome.Ptyxis'

    def available(self, ctx):
        return None if ctx.settings.has(self.schema) else 'Ptyxis is not installed'

    def changes(self, theme, ctx):
        c = theme.colors
        lines = [
            '[Palette]', f'Name={theme.name}', 'UseSystemAccent=false',
            f"Foreground={c['foreground']}", f"Background={c['background']}",
            f"CursorBackground={c['foreground']}", f"CursorForeground={c['background']}",
            f"TitlebarBackground={c['dark_background']}", f"TitlebarForeground={c['foreground']}",
            f"Color0={c['dark_background']}",
        ] + [f'Color{i}={c[f"color{i}"]}' for i in range(1, 16)]
        out = [File(data_home() / 'org.gnome.Ptyxis/palettes' / f'{theme.id}.palette', '\n'.join(lines) + '\n')]
        for uuid in ctx.settings.get(self.schema).get_strv('profile-uuids'):
            out.append(Setting('org.gnome.Ptyxis.Profile', 'palette', theme.id, f'/org/gnome/Ptyxis/Profiles/{uuid}/'))
        return out

    def reload(self, ctx):
        pass  # Ptyxis watches its palettes folder and profile settings


def jsonc(text):
    """Vicinae writes its config as JSON with // comment lines."""
    return json.loads(re.sub(r'^\s*//.*$', '', text, flags=re.M))


def set_theme_names(text, name):
    """Change only the theme names, keeping Vicinae's own formatting and comments."""
    start = text.index('"theme"')
    depth, end = 0, None
    for i in range(text.index('{', start), len(text)):
        depth += {'{': 1, '}': -1}.get(text[i], 0)
        if depth == 0:
            end = i
            break
    block = re.sub(r'("name"\s*:\s*")[^"]*"', lambda m: f'{m.group(1)}{name}"', text[start:end])
    return text[:start] + block + text[end:]


class Vicinae:
    name = 'vicinae'
    label = 'Vicinae launcher'

    def config_path(self):
        # The user service may pin a config file; fall back to the default one.
        unit = subprocess.run(['systemctl', '--user', 'cat', 'vicinae.service'],
                              capture_output=True, text=True).stdout
        pinned = re.findall(r'--config\s+(\S+)', unit)
        return pathlib.Path(pinned[-1]) if pinned else config_home() / 'vicinae/settings.json'

    def available(self, ctx):
        return None if (data_home() / 'vicinae').exists() else 'Vicinae is not installed'

    def changes(self, theme, ctx):
        c = theme.colors
        theme_id = f'omarchy-{theme.id}'
        toml = '\n'.join([
            '[meta]', 'version = 1', f'name = "{theme.name} (Omarchy)"',
            'description = "Generated by jade-theme from the Omarchy palette"',
            'variant = "dark"', 'inherits = "vicinae-dark"', '',
            '[colors.core]', f'background = "{c["background"]}"', f'foreground = "{c["foreground"]}"',
            f'secondary_background = "{c["dark_background"]}"', f'border = "{c["selection"]}"',
            f'accent = "{c["accent"]}"', f'accent_foreground = "{c["bright_foreground"]}"', '',
            '[colors.list.item.selection]', f'background = "{c["selection"]}"',
            f'secondary_background = "{c["lighter_background"]}"', '',
            '[colors.accents]',
        ] + [f'{name} = "{c[key]}"' for name, key in [
            ('blue', 'blue'), ('green', 'green'), ('magenta', 'magenta'), ('orange', 'orange'),
            ('purple', 'bright_magenta'), ('red', 'red'), ('yellow', 'bright_yellow'), ('cyan', 'cyan')]])
        out = [File(data_home() / 'vicinae/themes' / f'{theme_id}.toml', toml + '\n')]
        config = self.config_path()
        text = read_text(config)
        if text is not None:
            themes_now = jsonc(text).get('theme', {})
            names = [themes_now.get(v, {}).get('name') for v in ('dark', 'light')]
            if names != [theme_id, theme_id]:
                out.append(File(config, set_theme_names(text, theme_id)))
        return out

    def reload(self, ctx):
        text = read_text(self.config_path())
        name = jsonc(text).get('theme', {}).get('dark', {}).get('name') if text else None
        if name:
            subprocess.run(['vicinae', 'theme', 'set', name], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


class Kitty:
    name = 'kitty'
    label = 'Kitty terminal'

    def available(self, ctx):
        return None if (config_home() / 'kitty/kitty.conf').exists() else 'Kitty is not configured'

    def changes(self, theme, ctx):
        folder = config_home() / 'kitty'
        conf = read_text(folder / 'kitty.conf')
        # Included last, so it overrides the inline colors without deleting them.
        included = managed_block(conf, 'include jade-theme.conf')
        return [
            File(folder / 'jade-theme.conf', themes.render(themes.template('kitty.conf.tpl'), theme.colors)),
            File(folder / 'kitty.conf', included),
        ]

    def reload(self, ctx):
        signal('kitty', 'USR1')


class Starship:
    name = 'starship'
    label = 'Starship prompt'
    # The prompt refers to Catppuccin color names; give each a theme color.
    NAMES = {
        'rosewater': 'bright_foreground', 'mauve': 'magenta', 'red': 'red', 'peach': 'orange',
        'yellow': 'yellow', 'green': 'green', 'teal': 'cyan', 'sapphire': 'accent', 'blue': 'blue',
        'overlay1': 'dark_foreground', 'overlay0': 'muted',
    }

    def available(self, ctx):
        return None if (config_home() / 'starship.toml').exists() else 'Starship is not configured'

    def changes(self, theme, ctx):
        path = config_home() / 'starship.toml'
        text = read_text(path)
        text = re.sub(r'^palette\s*=.*$', 'palette = "jade"', text, count=1, flags=re.M)
        if not re.search(r'^palette\s*=', text, re.M):
            text = 'palette = "jade"\n' + text
        block = '[palettes.jade]\n' + '\n'.join(f'{k} = "{theme.colors[v]}"' for k, v in self.NAMES.items())
        return [File(path, managed_block(text, block))]

    def reload(self, ctx):
        pass  # read on every prompt


class Btop:
    name = 'btop'
    label = 'btop'

    def available(self, ctx):
        return None if (config_home() / 'btop/btop.conf').exists() else 'btop is not configured'

    def changes(self, theme, ctx):
        folder = config_home() / 'btop'
        conf = re.sub(r'^color_theme\s*=.*$', 'color_theme = "jade"', read_text(folder / 'btop.conf'), count=1, flags=re.M)
        return [
            File(folder / 'themes/jade.theme', themes.render(themes.template('btop.theme.tpl'), theme.colors)),
            File(folder / 'btop.conf', conf),
        ]

    def reload(self, ctx):
        signal('btop', 'USR2')


class VSCode:
    name = 'vscode'
    label = 'VS Code color theme'
    ID = 'jade-shell.jade-themes'
    VERSION = '1.0.0'

    def settings_path(self):
        return config_home() / 'Code/User/settings.json'

    def available(self, ctx):
        return None if self.settings_path().exists() else 'VS Code is not set up'

    @staticmethod
    def label_for(theme):
        return f'Jade · {theme.name}'

    def changes(self, theme, ctx):
        base = pathlib.Path.home() / '.vscode/extensions'
        folder = base / f'{self.ID}-{self.VERSION}'
        template = themes.template('vscode-theme.json.tpl')
        # One extension contributes every theme, so switching is a settings change.
        contributed, out = [], []
        for theme_id in themes.ids():
            t = theme if theme_id == theme.id else themes.load(theme_id)
            data = json.loads(themes.render(template, t.colors))
            data['name'] = self.label_for(t)
            out.append(File(folder / 'themes' / f'{t.id}.json', json.dumps(data, indent=2) + '\n'))
            contributed.append({'label': self.label_for(t), 'uiTheme': 'vs-dark', 'path': f'./themes/{t.id}.json'})
        package = {
            'name': 'jade-themes', 'displayName': 'Jade Shell themes', 'publisher': 'jade-shell',
            'version': self.VERSION, 'engines': {'vscode': '^1.60.0'},
            'categories': ['Themes'], 'contributes': {'themes': contributed},
        }
        out.append(File(folder / 'package.json', json.dumps(package, indent=2) + '\n'))

        registry = base / 'extensions.json'
        entries = json.loads(read_text(registry) or '[]')
        if not any(e.get('identifier', {}).get('id') == self.ID for e in entries):
            entries.append({
                'identifier': {'id': self.ID}, 'version': self.VERSION,
                'location': {'$mid': 1, 'fsPath': str(folder), 'external': folder.as_uri(), 'path': str(folder), 'scheme': 'file'},
                'relativeLocation': folder.name,
            })
            out.append(File(registry, json.dumps(entries)))

        settings = read_text(self.settings_path())
        line = f'"workbench.colorTheme": "{self.label_for(theme)}"'
        if re.search(r'"workbench\.colorTheme"\s*:\s*"[^"]*"', settings):
            settings = re.sub(r'"workbench\.colorTheme"\s*:\s*"[^"]*"', lambda _m: line, settings, count=1)
        else:
            settings = settings.replace('{', '{\n    ' + line + ',', 1)
        out.append(File(self.settings_path(), settings))
        return out

    def reload(self, ctx):
        pass  # VS Code watches settings.json
