/* Generated by jade-theme from the current theme; do not edit. */

/* Simple Workspaces Bar: numbers, active workspace filled with the accent. */
#panel .desktop-label {
    font-family: "JetBrains Mono";
    font-size: 9pt;
    font-weight: 400;
    margin: 0 2px;
    padding: 0 6px;
    border-radius: 0;
    border-bottom: 2px solid transparent;
    background-color: transparent;
    color: {{ muted }};
}
#panel .desktop-label-nonempty-inactive { color: {{ foreground }}; background-color: transparent; }
#panel .desktop-label-nonempty-active,
#panel .desktop-label-empty-active {
    color: {{ darker_background }};
    background-color: {{ accent }};
    font-weight: 700;
    border-radius: 4px;
    border-bottom: 2px solid {{ dark_foreground }};
}

/* Status icons: one size and spacing across extensions. */
#panel .panel-button .system-status-icon { icon-size: 16px; }
#panel .panel-status-menu-box { spacing: 8px; }

/* GNOME 50 split quick toggles: seamless tiles without accent seams. */
.popup-menu-content .quick-toggle-has-menu .quick-toggle-separator,
.popup-menu-content .quick-toggle-has-menu:checked .quick-toggle-separator {
    width: 0px;
    background-color: transparent !important;
}
.popup-menu-content .quick-toggle-has-menu .quick-toggle,
.popup-menu-content .quick-toggle-has-menu .quick-toggle-menu-button.icon-button,
.popup-menu-content .quick-toggle-has-menu .quick-toggle-menu-button.icon-button:checked:ltr,
.popup-menu-content .quick-toggle-has-menu .quick-toggle-menu-button.icon-button:checked:rtl {
    border-width: 0px !important;
    border-color: transparent !important;
    box-shadow: none !important;
}
.popup-menu-content .quick-toggle-has-menu .quick-toggle-menu-button.icon-button {
    background-color: {{ lighter_background }} !important;
    color: {{ foreground }} !important;
}
.popup-menu-content .quick-toggle-has-menu .quick-toggle-menu-button.icon-button:checked {
    background-color: {{ selection }} !important;
}
.popup-menu-content .quick-toggle-has-menu .quick-toggle-menu-button.icon-button:ltr {
    border-radius: 0px 6px 6px 0px !important;
}
.popup-menu-content .quick-toggle-has-menu .quick-toggle-menu-button.icon-button:rtl {
    border-radius: 6px 0px 0px 6px !important;
}
.popup-menu-content .quick-toggle-has-menu .quick-toggle-menu-button.icon-button:hover,
.popup-menu-content .quick-toggle-has-menu .quick-toggle-menu-button.icon-button:checked:hover {
    background-color: {{ quick_toggle_hover }} !important;
}
.popup-menu-content .quick-toggle-has-menu .quick-toggle:focus,
.popup-menu-content .quick-toggle-has-menu .quick-toggle-menu-button.icon-button:focus,
.popup-menu-content .quick-toggle-has-menu .quick-toggle-menu-button.icon-button:checked:focus {
    box-shadow: inset 0 0 0 1px rgba({{ foreground_rgb }}, 0.5) !important;
}

/* Jade Shell theme picker: framed like an Omarchy panel. The doubled class
 * outranks panel themers (OpenBar) that restyle every popup with !important. */
.popup-menu-content.jade-picker {
    background-color: {{ background }} !important;
    border: 2px solid {{ accent }} !important;
    border-radius: 0 !important;
    box-shadow: none !important;
}
.jade-picker { color: {{ foreground }}; }
.jade-picker .jade-title { color: {{ light_foreground }}; }
.jade-picker .jade-meta,
.jade-picker .jade-section,
.jade-picker .jade-status { color: {{ secondary_text }}; }
.jade-picker .jade-status.jade-error { color: {{ bright_red }}; }
.jade-picker .jade-hero-icon { color: {{ accent }}; }
.jade-picker .jade-divided { border-top: 1px solid {{ selection }}; }
.jade-picker .jade-tile { border: 2px solid rgba({{ foreground_rgb }}, 0.12); background-color: {{ dark_background }}; }
.jade-picker .jade-tile:hover { border-color: rgba({{ foreground_rgb }}, 0.6); }
.jade-picker .jade-tile:focus { border-color: {{ foreground }}; }
.jade-picker .jade-tile.jade-current { border-color: {{ accent }}; }
.jade-picker .jade-tile-name { color: {{ foreground }}; }
.jade-picker .jade-tile.jade-current .jade-tile-name { color: {{ light_foreground }}; }
.jade-picker .jade-action { border: 1px solid rgba({{ foreground_rgb }}, 0.4); color: {{ foreground }}; }
.jade-picker .jade-action:hover { background-color: {{ selection }}; border-color: {{ foreground }}; color: {{ light_foreground }}; }
.jade-picker .jade-action:focus { box-shadow: inset 0 0 0 1px {{ dark_foreground }}; }

/* Jade AI Usage (osaka-ai-usage@local). One class more specific than its own
 * Osaka Jade stylesheet, so these win whichever extension loaded last. Its
 * painted meters read colors.json instead. */
#panel .panel-button.osaka-ai-panel .ai-panel-text,
#panel .panel-button.osaka-ai-panel .ai-panel-icon { color: {{ foreground }}; }
#panel .panel-button.osaka-ai-panel .ai-panel-icon.ai-alarm { color: {{ bright_red }}; }
.popup-menu-boxpointer .popup-menu-content.osaka-ai-menu {
    background-color: {{ background }} !important;
    border: 2px solid {{ accent }} !important;
}
.popup-menu-boxpointer .osaka-ai-menu { color: {{ foreground }}; }
.popup-menu-boxpointer .osaka-ai-menu .ai-text { color: {{ foreground }}; }
.popup-menu-boxpointer .osaka-ai-menu .ai-caption,
.popup-menu-boxpointer .osaka-ai-menu .ai-section,
.popup-menu-boxpointer .osaka-ai-menu .ai-hero-meta,
.popup-menu-boxpointer .osaka-ai-menu .ai-day-name,
.popup-menu-boxpointer .osaka-ai-menu .ai-day-value,
.popup-menu-boxpointer .osaka-ai-menu .ai-model-value { color: {{ secondary_text }}; }
.popup-menu-boxpointer .osaka-ai-menu .ai-urgent,
.popup-menu-boxpointer .osaka-ai-menu .ai-value.ai-urgent,
.popup-menu-boxpointer .osaka-ai-menu .ai-hero-meta.ai-urgent,
.popup-menu-boxpointer .osaka-ai-menu .ai-action.ai-failed { color: {{ bright_red }}; }
.popup-menu-boxpointer .osaka-ai-menu .ai-jade,
.popup-menu-boxpointer .osaka-ai-menu .ai-hero-icon { color: {{ dark_foreground }}; }
.popup-menu-boxpointer .osaka-ai-menu .ai-hero-title,
.popup-menu-boxpointer .osaka-ai-menu .ai-value,
.popup-menu-boxpointer .osaka-ai-menu .ai-today .ai-day-name,
.popup-menu-boxpointer .osaka-ai-menu .ai-today .ai-day-value,
.popup-menu-boxpointer .osaka-ai-menu .ai-model-row:hover .ai-model-value { color: {{ light_foreground }}; }
.popup-menu-boxpointer .osaka-ai-menu .ai-divided,
.popup-menu-boxpointer .osaka-ai-menu .ai-footer-item { border-top-color: {{ selection }}; }
.popup-menu-boxpointer .osaka-ai-menu .ai-chip,
.popup-menu-boxpointer .osaka-ai-menu .ai-action { border-color: rgba({{ foreground_rgb }}, 0.4); color: {{ foreground }}; }
.popup-menu-boxpointer .osaka-ai-menu .ai-chip:hover { background-color: rgba({{ foreground_rgb }}, 0.08); }
.popup-menu-boxpointer .osaka-ai-menu .ai-chip:checked,
.popup-menu-boxpointer .osaka-ai-menu .ai-action:hover { background-color: {{ selection }}; border-color: {{ foreground }}; color: {{ light_foreground }}; }
.popup-menu-boxpointer .osaka-ai-menu .ai-chip:focus,
.popup-menu-boxpointer .osaka-ai-menu .ai-action:focus { box-shadow: inset 0 0 0 1px {{ dark_foreground }}; }
.popup-menu-boxpointer .osaka-ai-menu .ai-action:insensitive { color: {{ secondary_text }}; }
.popup-menu-boxpointer .osaka-ai-menu .ai-card { border-color: rgba({{ bright_red_rgb }}, 0.35); background-color: rgba({{ bright_red_rgb }}, 0.08); }
