/* Generated by jade-theme from the current theme; do not edit. */

/* Simple Workspaces Bar: numbers, active workspace filled with the accent. */
#panel .desktop-label {
    font-family: "JetBrains Mono";
    font-size: 9pt;
    font-weight: 400;
    margin: 0 2px;
    padding: 0 6px;
    border-radius: 0;
    border-bottom: 2px solid transparent;
    background-color: transparent;
    color: {{ muted }};
}
#panel .desktop-label-nonempty-inactive { color: {{ foreground }}; background-color: transparent; }
#panel .desktop-label-nonempty-active,
#panel .desktop-label-empty-active {
    color: {{ darker_background }};
    background-color: {{ accent }};
    font-weight: 700;
    border-radius: 4px;
    border-bottom: 2px solid {{ dark_foreground }};
}

/* Status icons: one size and spacing across extensions. */
#panel .panel-button .system-status-icon { icon-size: 16px; }
#panel .panel-status-menu-box { spacing: 8px; }

/* GNOME 50 split quick toggles: seamless tiles without accent seams. */
.popup-menu-content .quick-toggle-has-menu .quick-toggle-separator,
.popup-menu-content .quick-toggle-has-menu:checked .quick-toggle-separator {
    width: 0px;
    background-color: transparent !important;
}
.popup-menu-content .quick-toggle-has-menu .quick-toggle,
.popup-menu-content .quick-toggle-has-menu .quick-toggle-menu-button.icon-button,
.popup-menu-content .quick-toggle-has-menu .quick-toggle-menu-button.icon-button:checked:ltr,
.popup-menu-content .quick-toggle-has-menu .quick-toggle-menu-button.icon-button:checked:rtl {
    border-width: 0px !important;
    border-color: transparent !important;
    box-shadow: none !important;
}
.popup-menu-content .quick-toggle-has-menu .quick-toggle-menu-button.icon-button {
    background-color: {{ lighter_background }} !important;
    color: {{ foreground }} !important;
}
.popup-menu-content .quick-toggle-has-menu .quick-toggle-menu-button.icon-button:checked {
    background-color: {{ selection }} !important;
}
.popup-menu-content .quick-toggle-has-menu .quick-toggle-menu-button.icon-button:ltr {
    border-radius: 0px 6px 6px 0px !important;
}
.popup-menu-content .quick-toggle-has-menu .quick-toggle-menu-button.icon-button:rtl {
    border-radius: 6px 0px 0px 6px !important;
}
.popup-menu-content .quick-toggle-has-menu .quick-toggle-menu-button.icon-button:hover,
.popup-menu-content .quick-toggle-has-menu .quick-toggle-menu-button.icon-button:checked:hover {
    background-color: {{ quick_toggle_hover }} !important;
}
.popup-menu-content .quick-toggle-has-menu .quick-toggle:focus,
.popup-menu-content .quick-toggle-has-menu .quick-toggle-menu-button.icon-button:focus,
.popup-menu-content .quick-toggle-has-menu .quick-toggle-menu-button.icon-button:checked:focus {
    box-shadow: inset 0 0 0 1px rgba({{ foreground_rgb }}, 0.5) !important;
}
