# Jade Shell's tmux colors: styles only, so a status line of your own keeps
# its contents. `set -gq`: older tmux versions skip the options they lack.
set -gq status-style "bg=default,fg={{ foreground }}"
set -gq window-status-style "fg={{ muted }}"
set -gq window-status-current-style "fg={{ accent }},bold"
set -gq window-status-activity-style "fg={{ yellow }}"
set -gq window-status-bell-style "fg={{ red }},bold"
set -gq pane-border-style "fg={{ muted }}"
set -gq pane-active-border-style "fg={{ accent }}"
set -gq message-style "bg=default,fg={{ accent }}"
set -gq message-command-style "bg=default,fg={{ accent }}"
set -gq mode-style "bg={{ accent }},fg={{ background }}"
set -gq copy-mode-match-style "bg={{ selection_background }},fg={{ foreground }}"
set -gq copy-mode-current-match-style "bg={{ accent }},fg={{ background }}"
set -gq popup-border-style "fg={{ accent }}"
set -gq menu-style "bg={{ background }},fg={{ foreground }}"
set -gq menu-selected-style "bg={{ accent }},fg={{ background }}"
set -gq menu-border-style "fg={{ accent }}"
set -gwq clock-mode-colour "{{ accent }}"
